all:Ex3q1 Ex3q2a ex3q2b Ex3q3a Ex3a3b
    gcc Ex3q1.o Ex3q2a.o Ex3q2b.o Ex3q3a.o Ex3a3b.o -O app

Ex3q1:Ex3q1.c
        gcc Ex3q1.c -o Ex3q1

ex3q2a:Ex3q2a.c
         gcc Ex3q2a.c -o Ex3q2a 

ex3q2b:ex3q2b.c
         gcc Ex3q2b.c -o Ex3q2b 

ex3q3a:Ex3q3a.c
         gcc -o Ex3q3a Ex3q3a.c 

ex3q3b:Ex3q3b.c
         gcc -o Ex3q3b Ex3q3b.c -pthread